doc/001_Samples/001_Samples/example_1/django_courses/django_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("lesson_1/", include("lesson_1.urls")),
    path("admin/", admin.site.urls),
]

doc/001_Samples/001_Samples/example_1/django_courses/lesson_1/urls.py
from django.urls import path
from lesson_1 import views

urlpatterns = [
    path("", views.index, name="index"),
]

doc/001_Samples/django_courses/django_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("lesson_1/", include("lesson_1.urls")),
    path("admin/", admin.site.urls),
]

doc/001_Samples/django_courses/lesson_1/urls.py
from django.urls import path

from . import views


urlpatterns = [path("", views.index, name="index")]

doc/001_Samples/lesson1/lesson1/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

pr1101/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("rent/", include("rent_things.urls", namespace="rent_app")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent_things/urls.py
from django.urls import path
from rent_things.views import index, ThingListView, CategoryListView


app_name = "rent_app"

urlpatterns = [
    path("", index, name="index"),
    path("things/", ThingListView.as_view(), name="things_list"),
    path("categories/", CategoryListView.as_view(), name="category_list"),
]

doc/001_Samples/001_Samples/example_1/django_courses/lesson_1/models.py
from django.db import models

# Create your models here.

doc/001_Samples/django_courses/lesson_1/models.py
from django.db import models

# Create your models here.

rent_things/models.py
from pathlib import Path
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify

User = get_user_model()


def get_image_path(instance, filename: str, subfolder: Path = Path("uploads")) -> Path:
    filename = (
        f"{slugify(filename.partition(".")[0])}_{uuid4()}" + Path(filename).suffix
    )
    return Path(subfolder) / filename


class Image(models.Model):
    image = models.ImageField(upload_to=get_image_path)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.image.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="children",
    )

    class Meta:
        verbose_name_plural = "categories"
        ordering = ["name", "parent__name"]
        unique_together = ["name", "parent"]

    def __str__(self):
        return self.name


class Tag(models.Model):
    TAG_PREFIX = "##"
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.name = self.name.translate(str.maketrans(" ", "_", ".,;:!?#")).lower()
        self.name = self.TAG_PREFIX + self.name
        return super().save(force_insert, force_update, using, update_fields)


class Thing(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="things"
    )
    tags = models.ManyToManyField(Tag, related_name="things")
    is_active = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    compensation = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="things")
    images = models.ManyToManyField(Image, blank=True, related_name="things")

    class Meta:
        ordering = ["name", "created_at"]

    def __str__(self):
        return self.name


class Displacement(models.Model):
    class Condition(models.TextChoices):
        NEW = "N", "New - traces of use are imperceptible"
        EXCELLENT = "E", "Excellent - traces of use are minimal"
        GOOD = "G", "Good - visible signs of use"
        SATISFACTORY = "S", "Satisfactory - significant traces of use, but possible use"
        BAD = "B", "Bad - the item is damaged, but can be repaired"
        VERY_BAD = "VB", "Very bad - the item is damaged and cannot be repaired"

    thing = models.ForeignKey(
        Thing, on_delete=models.CASCADE, related_name="displacements"
    )
    to = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="displacements",
        help_text="User to whom the thing is displaced",
    )
    by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="supported_displacements",
        help_text="User who displaced the thing",
    )
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    condition = models.CharField(
        max_length=2, choices=Condition, default=Condition.EXCELLENT
    )

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return f"{self.thing} -> {self.to} by {self.by}"

user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

doc/001_Samples/001_Samples/example_1/django_courses/lesson_1/views.py
from django.shortcuts import render


def index(request):
    return render(request, "index.html")

doc/001_Samples/django_courses/lesson_1/views.py
# from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world! Вы на странице 1 занятия")

rent_things/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render
from django.views import generic

from .models import Thing, Category, Tag


def index(request: HttpRequest) -> HttpResponse:
    num_things = Thing.objects.count()
    num_categories = Category.objects.count()
    num_tags = Tag.objects.count()
    context = {
        "num_things": num_things,
        "num_categories": num_categories,
        "num_tags": num_tags,
    }
    return render(request, "rent_things/index.html", context=context)


class ThingListView(generic.ListView):
    model = Thing
    template_name = (
        "rent_things/things_list.html"  # Default: <app_label>/<model_name>_list.html
    )
    context_object_name = "things"  # Default: object_list
    queryset = Thing.objects.filter(is_active=True).select_related(
        "category"
    )  # Default: Model.objects.all()


class CategoryListView(generic.ListView):
    model = Category
    context_object_name = "categories"

user/views.py
from django.shortcuts import render

# Create your views here.

doc/001_Samples/001_Samples/example_1/django_courses/lesson_1/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>My first html page!!!</h1>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Things</title>
  {% endblock %}
  {% load static %}
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include 'includes/sidebar.html' %}
      {% endblock %}

    </div>
    <div class="col-sm-9">
      {% block content %}
        Content
      {% endblock %}
    </div>

  </div>

</body>
</html>

templates/includes/sidebar.html
{% block sidebar %}
  <ul class="sidebar-nav">
    <li><a href="{% url 'rent_app:index' %}">Home</a></li>
    <li><a href="{% url 'rent_app:things_list' %}">Things</a></li>
    <li><a href="{% url 'rent_app:category_list' %}">Categories</a></li>
    <li><a href="#">Tags</a></li>
  </ul>
{% endblock %}

templates/rent_things/category_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Categories:</h1>
  <hr>
  {% if categories %}
    <ul>
      {% for category in categories %}
        <li>
          <a href="#">{{ category.name }}</a> (<a style="color: aqua" href="#">{{ category.things.count }}</a>)
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no categories in the database.</p>
  {% endif %}
{% endblock %}

templates/rent_things/index.html
{% extends 'base.html' %}

{% block title %}
  <title>Home page</title>
{% endblock %}

{% block content %}
  <h1>Welcome to a world where things live a full life!</h1>
  <hr>
  <ul>
    <li>There are {{ num_things }} things in the database.</li>
    <li>There are {{ num_categories }} categories in the database.</li>
    <li>There are {{ num_tags }} tags in the database.</li>
  </ul>
{% endblock %}

templates/rent_things/things_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Things:</h1>
  <hr>
  {% if things %}
    <ul>
      {% for thing in things %}
        <li>
          <a href="#">{{ thing.name }}</a> (<a style="color: aqua" href="#">{{ thing.category }}</a>)</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no things in the database.</p>
  {% endif %}
{% endblock %}